export const db = "main-stackoverflow"
export const questionCollection = "question"
export const answerCollection = "answers"
export const commentCollection = "comments"
export const voteCollection = "votes"
export const questionAttachmentBucket = "question-attachment"